Add log out button
Code-4-Community/frontend-scaffold pull request #36
Opened 2021-03-21 22:28 UTC by anirudh723

Closes issue #67 in [LLB frontend](https://github.com/Code-4-Community/lucys-love-bus-frontend/issues/67).

This PR adds a log out button to the dropdown of the navigation bar. I added a "Log Out" menu item, and upon click, it removes the state in the localStorage, and routes the user to the home page. 

Screenshots:

Log out button:
![image](https://user-images.githubusercontent.com/46979800/111922889-e81c3680-8a72-11eb-90f8-569644fd2210.png)

Before logging in (localStorage is empty):
![image](https://user-images.githubusercontent.com/46979800/111922905-f9fdd980-8a72-11eb-935f-89b70b1a54d3.png)

After logging in (localStorage is updated with state):
![image](https://user-images.githubusercontent.com/46979800/111922915-0aae4f80-8a73-11eb-943d-86ac2ca77324.png)

After clicking the newly added log out button, back at the home page (localStorage is cleared out):
![image](https://user-images.githubusercontent.com/46979800/111922969-34677680-8a73-11eb-991f-c4c81fa503e4.png)

cc: @varunthakkar1

2021-03-23 17:10 UTC, jackblanc requested changes
You've got the right idea, but a lot of this logic already lives in a thunk, logoutUser. We should continue to use that thunk so that logout behavior is the same in any place we call it.

2021-03-23 17:10 UTC, jackblanc commented on src/components/navbar/index.tsx
> +            });
This should be done by `dispatch(logoutUser())`, we have a thunk which makes this request and clears the store.

2021-03-23 19:53 UTC, rymaju commented
https://github.com/Code-4-Community/frontend-scaffold/pull/39

Is relevant here, you can now use logout and it will clear tokens for you!

2021-03-24 12:53 UTC, rymaju commented on src/components/navbar/index.tsx
> +            history.go(0); // force refresh if user is already on home page
force refresh here is actually pretty big brain, I kind of like it 😄 

I think we should still use the thunk from master but this is super creative

2021-03-29 13:43 UTC, rymaju approved these changes

2021-03-29 13:43 UTC, rymaju commented on src/components/navbar/index.tsx
> +            history.go(0); // force refresh if user is already on home page
⛏️ We dont _need_ to force refresh anymore, I dont really mind if we do though 🤷

2021-03-30 17:28 UTC, jackblanc approved these changes
Nice work. For bonus points (we can pair on this) we should add a Jest/Enzyme test for the button click. That's not something we've done before, but would be beneficial to start.

2021-03-31 19:16 UTC, merged